### ISSUE TITLE
.col-gold-sm is a negative percentage, becomes 100%

### ISSUE THREAD

**Issue by Merovex** [iamkevinrhodes/goldbootstrap#2]
.col-gold-sm {
  float: left;
  position: relative;
  min-height: 1px;
  padding-left: (@grid-gutter-width / 2);
  padding-right: (@grid-gutter-width / 2);
  width: percentage(@gold-ratio-1);
}

This is the code from your less. When I applied it, the value of @gold-ratio-1 was -61.8%, which was interpreted by Chrome as 100%.

I changed it to:

$gold-ratio-1:          1 - $gold-ratio-2; // 0.382

**Comment by kttmnn** [comment]
good job. Thanks

**Comment by kevinrhodesdesign** [comment]
I updated this in the latest release. Thanks!
