### ISSUE TITLE
Drop-in?

### ISSUE THREAD

**Issue by jdahdah** [iamkevinrhodes/goldbootstrap#3]
Hey Kevin,

first off, thanks for sharing this project, it seems like it could come in handy. I'm just a little confused about the structure. Did you make any changes to the core Bootstrap Less files or why are you including the entire framework in this repository? Would it work if I included only `goldbootstrap.less` as an extra plugin and otherwise stuck to the regular Bootstrap repository?

**Comment by kevinrhodesdesign** [comment]
Hey, thanks for your interest. No the core Bootstrap is untouched. My file, goldbootstrap.less overwrites anything that needs changes. This includes the entire framework. I'll include that clarity in the documentation for the June 30 2016 release. You'd have to modify the GoldBootstrap file a little if you wanted to use it without Bootstrap. I don't plan on doing that right now.
