### ISSUE TITLE
Not responsive?

### ISSUE THREAD

**Issue by edmobm** [iamkevinrhodes/goldbootstrap#5]
I put col-sm-12 with col-gold-lg or sm but it's not changing the width to 100% on small screens, it still using the width of col-gold-.

``` html
<div class="row">
<div class="col-sm-12 col-gold-lg">
</div>
<div class="col-sm-12 col-gold-sm">
</div>
</div>
```

**Comment by kttmnn** [comment]
I add these lines at the bottom of my goldboostrap.less:

`
@media (max-width: 991px) {
    .col-gold-sm, .col-gold-lg {
        width: 100%;
    }
}
`

**Comment by kevinrhodesdesign** [comment]
I originally thought people would want to retain the gold columns, even on mobile. Seems like you guys want to drop the Gold Columns, and instead, flex to 100%. I'll include this in the June 30 2016 update.
